Sunnysideup\Schedulizer\ConfiguredSchedule:
  schedule_range_precedence:
    - Sunnysideup\Schedulizer\ScheduleRange
    - Sunnysideup\Schedulizer\ScheduleRangeDay
    - Sunnysideup\Schedulizer\ScheduleRangeDayType
    - Sunnysideup\Schedulizer\ScheduleRangeDefault
